spring:
  application:
    name: kafka-example
  kafka:
    bootstrap-servers: http://localhost:9092

    properties:
      schema.registry.url: http://localhost:8081
      specific.avro.reader: true

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer

kafka:
  topic: customer-creation-topic
  groupId: example-group-id