version: '3.8'

services:
  mongo-test:
    image: mongo
    volumes:
      - $HOME/data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/demodb --quiet
      interval: 2s
      timeout: 5s
      retries: 10
    container_name: mongodb-test

  app:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - MONGO_URL=mongodb://mongo-test:27017/demodb
    command: java -jar app.jar
    ports:
      - "8080:8080"
    depends_on:
      mongo-test:
        condition: service_healthy
    container_name: hexagonal-example